services:

  db:
    image: mysql:8
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - ~/applications/silentstorm/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: silentstorm
    ports:
      - "13306:3306"

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:3
    restart: unless-stopped
    volumes:
      - ~/applications/silentstorm/lavalink/application.yml:/opt/Lavalink/application.yml
      - ~/applications/silentstorm/lavalink/plugins:/opt/Lavalink/plugins
    ports:
      - "12333:2333"

